[versions]
ktor_version = "2.3.7"
dagger_version = "2.48"
kotlin_serialization_version = "1.6.2"

[libraries]
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor_version" }
ktor-client-content-negotiation = {module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor_version"}
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor_version" }
ktor-client-logging= { module = "io.ktor:ktor-client-logging", version.ref = "ktor_version" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor_version" }

google-dagger = { module = "com.google.dagger:dagger", version.ref = "dagger_version" }
google-dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger_version" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin_serialization_version" }
